### ISSUE TITLE
TypeError (NodeJS integration)

### ISSUE THREAD

**Issue by ghost** [socsieng/sendkeys-macos#2]
```
const sendKeys = require('/Users/censored/Documents/sendkeys-macos');

sendKeys(
  // name of application to send keystrokes to
  'Google Chrome',
  // keystrokes to send
  '<c:v:command><c:enter>',
  {
    // delay before sending keystrokes,
    // need to give the application a chance to activate before sending keystrokes
    initialDelay: 1,
  });

function pbcopy(data) {
    var proc = require('child_process').spawn('pbcopy'); 
    proc.stdin.write(data); proc.stdin.end();
}
function timeout() {
    setTimeout(function () {
			var x;
			x = ""
			for (var i=0; i<1800; i++) {
			x+=String.fromCharCode(Math.floor(Math.random()*0x1D300)+0x800)
			}
pbcopy(x)
sendKeys()


        timeout();
    }, 250);
}


timeout()
```

All of my code is in a .js file which I run from command line using sudo node <filename>

It is supposed to go to chrome and copy paste the string x that's generated (everything is working, it copies the string x and I can paste it manually) but sendKeys() encounters an error:

```
/Users/censored/Documents/sendkeys-macos/src/generator.js:13
  const lines = text.split(lineEndingExpression);
                     ^

TypeError: Cannot read property 'split' of undefined
    at Object.generate (/Users/censored/Documents/sendkeys-macos/src/generator.js:13:22)
    at sendKeys (/Users/censored/Documents/sendkeys-macos/src/index.js:15:28)
    at Timeout._onTimeout (/Users/censored/Documents/bot.js:26:1)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by socsieng** [comment]
The problem is:

> ```
> pbcopy(x)
> sendKeys()
>```

You haven't passed in any parameters.

You should be using parameters from the snippet as an example:

```cs
sendKeys(
  // name of application to send keystrokes to
  'Google Chrome',
  // keystrokes to send
  '<c:v:command><c:enter>',
  {
    // delay before sending keystrokes,
    // need to give the application a chance to activate before sending keystrokes
    initialDelay: 1,
  });
```

**Comment by ghost** [comment]
2 improvements / things to note
`'<c:v:command><p:10:c:enter>' `
sends the second part, <p:10:c:enter> as a string (directly shown on screen instead of the keypress)
and also, the code seems to work if I don't put the sendKeys() into the loop

**Comment by socsieng** [comment]
The way the command handles instructions is `<c:v:command><p:10><c:enter>`, note that `<p:10>` and `<c:enter>` are separate instructions.

Can you include a code sample on how you are using `sendKeys()` in a loop and any errors you are receiving?

**Comment by socsieng** [comment]
Note another way to achieve this with the command line is something like:

``` sh
printf "hello world" | clipcopy && sendkeys -a "Visual Studio Code" -c "<c:v:command><p:1><c:return>"
```

**Comment by ghost** [comment]
I think I just figured it out, will test right now ( I did something retarded oof)
ok this code seems to be working with the exception that for some reason the enter is not registered properly. (its registered properly on terminal but google doesn't like it for some reason)
code:
```
const sendKeys = require('/Users/canmavi/Documents/sendkeys-macos');

function spam() {
sendKeys(
  // name of application to send keystrokes to
  'Google Chrome',
  // keystrokes to send
  '<c:v:command><p:1><c:enter>',
  
  {
    // delay before sending keystrokes,
    // need to give the application a chance to activate before sending keystrokes
    initialDelay: 0.2,
  });
}
p=0

function pbcopy(data) {
    var proc = require('child_process').spawn('pbcopy'); 
    proc.stdin.write(data); proc.stdin.end();
}
function timeout() {
    setTimeout(function () {
			var x;
			x = ""
			for (var i=0; i<1800; i++) {
			x+=String.fromCharCode(Math.floor(Math.random()*0x1D300)+0x800)
			}
pbcopy(x)
spam()
p++
		if (p<10) {
        timeout();
        }
    }, 250);
}


timeout()
```

**Comment by ghost** [comment]
its working like this, only doesnt press enter. I believe that part is a bug with google chrome and not the program, because it works on terminal and other apps.

**Comment by socsieng** [comment]
Try `return` instead of `enter`. They’re two different character codes for some reason.

**Comment by ghost** [comment]
ah! thank you :D
will edit this post when I can test it (not able to test atm)
