### ISSUE TITLE
PList Requirements for inclusion in a Hardened Runtime

### ISSUE THREAD

**Issue by fwiwDev** [socsieng/sendkeys-macos#9]
Hi socsieng!

Question:

This is an outstanding library that works quite well in development but when I attempt to build and notarize as a hardened runtime, it won't fully start. The window opens but nothing load. I have tried adding all of the Runtime Exception PList entitlements ([https://developer.apple.com/documentation/security/hardened_runtime](https://developer.apple.com/documentation/security/hardened_runtime)) but that does not help. Are there any hardened runtime/notarized apps that include this library as a dependency you know of? It would be super helpful to get some tips as to what I need to do to continue releasing my apps as hardened runtime/notarized, despite needing the functionality of sendkeys-macos.

When launching the app after building as a hardened runtime, the system console has errors like, "failed to lookup DARWIN_USER_CACHE_DIR" (subsystem com.apple.runningboard for my app) and "Failed to create LSApplicationRecord for ... 'The operation couldn't be completed.  (OSStatus error -10814.)"

Thank you!

**Comment by socsieng** [comment]
> Are there any hardened runtime/notarized apps that include this library as a dependency you know of?

No, not that I know of.

Unfortunately, I have no experience with app notarization.

How are you building/packaging your app? I wonder how hardening works with external app dependencies. In this case, the library has dependencies on NodeJS and osascript. Is that compatible with hardening?

**Comment by fwiwDev** [comment]
This is an electron app and I use electron builder to package it. I tried removing the notarization step and told the builder not to build it as a hardened runtime and the same thing occurs. I sure wish I could get it working as it is absolutely flawless in the development environment.

I have many other NodeJS libraries so I know it will work with that. I wonder about osascript though. Is that compatible with Mac OS Big Sur?

I also may attempt this [https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection](https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection) to see what the OS says with the compiled app and try to rule things out... Right now, I don't think this is related to notarizing or hardening the runtime.

Thanks so much for the quick reply by the way!

**Comment by socsieng** [comment]
>  I wonder about osascript though. Is that compatible with Mac OS Big Sur?

I'm not currently on Big Sur but I've been told that it works.

**Comment by fwiwDev** [comment]
K - it was not this library. Sorry for taking your time but I appreciate your support!

The issue was that I was loading things too early in my program so before electron was done with it's startup, I was trying to load this library even though I was not going to use it until later on.

It is now working exceptionally well. Thanks again for this AWESOME library and your super responsiveness!!

**Comment by socsieng** [comment]
No problem. Glad the library is of use to you. Curious about how you are using it, are you able to share any details about the electron app you are building?

**Comment by socsieng** [comment]
FYI, I've ported this tool over to Swift which includes support for mouse commands: https://github.com/socsieng/sendkeys
